language: python
python:
  - "2.6"
  - "2.7"
services:
  - riak
  - postgresql
  - redis-server
install:
  # We easy_install a binary riak_pb package because pip install needs `protoc'.
  - "easy_install 'riak_pb<1.3.0'"
  # For some reason we need these two as well.
  - "pip install https://github.com/praekelt/vumi/tarball/develop#egg=vumi-dev --use-mirrors"
  - "pip install https://github.com/praekelt/vumi-wikipedia/tarball/develop#egg=vumi-wikipedia-dev --use-mirrors"
  - "pip install -r requirements.pip --use-mirrors"
  - "pip install -r requirements-pytest.pip --use-mirrors"
before_script:
  - "psql -c 'create database go;' -U postgres"
  - "export PYTHONPATH=."
  - "django-admin.py syncdb --migrate --noinput --settings=go.testsettings" 
script: VUMITEST_REDIS_DB=1 ./run-tests.sh
after_script:
  - "psql -c 'drop database go;' -U postgres"