wikipedia_ussd:
    class: go.apps.wikipedia.vumi_app.WikipediaApplication
    config:
        metrics_prefix: wikipedia_ussd_application
        sms_transport: wikipedia_sms_transport
        incoming_sms_transport: wikipedia_sms_transport
        max_sms_content_length: 450
        max_sms_unicode_length: 190
        redis_manager:
          key_prefix: "vumigo"
          db: 1
        riak_manager:
          bucket_prefix: vumigo.
        middleware:
          - logging_mw: vumi.middleware.logging.LoggingMiddleware

# NOTE: This is a terrible hack to have an application claim the
#       wikipedia_sms_transport queue. We need this so that the
#       application_message_dispatcher.yaml is properly notified
#       of which queues need to be listened on.
#
#       Our big routing rewrite addresses specifically problems
#       like these.
wikipedia_sms:
    class: go.apps.wikipedia.vumi_app.WikipediaApplication
    config:
        metrics_prefix: wikipedia_ussd_application
        sms_transport: wikipedia_sms_transport
        incoming_sms_transport: wikipedia_sms_transport
        max_sms_content_length: 450
        max_sms_unicode_length: 190
        redis_manager:
          key_prefix: "vumigo"
          db: 1
        riak_manager:
          bucket_prefix: vumigo.
        middleware:
          - logging_mw: vumi.middleware.logging.LoggingMiddleware
